version: "3" # docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" #sync project dir with container dir
    ports:
      - 8080:80
      - 443:433
    
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=first_weack
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    #volumes:
    # - "./db:/docker-entrypoints-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  composer_cli:
    image: composer:latest
    volumes:
      - .:/app
    working_dir: /app
    command: composer install
